function uncheckAllDistricts(){
        document.getElementById("dCh_2").checked=false;
        document.getElementById("dCh_3").checked=false;
        document.getElementById("dCh_4").checked=false;
        document.getElementById("dCh_5").checked=false;
        document.getElementById("dCh_6").checked=false;
        document.getElementById("dCh_7").checked=false;
        document.getElementById("dCh_8").checked=false;
        document.getElementById("dCh_9").checked=false;
        document.getElementById("dCh_10").checked=false;
        document.getElementById("dCh_11").checked=false;
        document.getElementById("dCh_12").checked=false;
        document.getElementById("dCh_13").checked=false;
        document.getElementById("dCh_14").checked=false;
        document.getElementById("dCh_15").checked=false;
        document.getElementById("dCh_16").checked=false;
        document.getElementById("dCh_17").checked=false;
        document.getElementById("dCh_18").checked=false;
        document.getElementById("dCh_19").checked=false;
        document.getElementById("dCh_20").checked=false;
        document.getElementById("dCh_21").checked=false;
        document.getElementById("dCh_22").checked=false;
        document.getElementById("dCh_23").checked=false;
        document.getElementById("dCh_24").checked=false;
        document.getElementById("dCh_25").checked=false;
        document.getElementById("dCh_26").checked=false;
        document.getElementById("dCh_27").checked=false;
        document.getElementById("dCh_28").checked=false;
        document.getElementById("dCh_29").checked=false;
        document.getElementById("dCh_30").checked=false;
    }
    function checkAllYears(){
        document.getElementById("yCh_2").checked=false;
        document.getElementById("yCh_3").checked=false;
        document.getElementById("yCh_4").checked=false;
        document.getElementById("yCh_5").checked=false;
        document.getElementById("yCh_6").checked=false;
        document.getElementById("yCh_7").checked=false;
    }
    function uncheckEntireState(id){
        document.getElementById(id).checked=false;
    }